name: depicter_env
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge/label/cf201901
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.5.0
  - alsa-lib=1.2.8
  - anndata=0.6.22.post1
  - anyio=3.5.0
  - aom=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attr=2.5.1
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.3
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.7.1
  - ca-certificates=2023.05.30
  - cached-property=1.5.2
  - cachetools=3.0.0
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.1
  - charset-normalizer=2.1.1
  - click=7.0
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.3.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.3.1
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - dav1d=1.0.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.9.0
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.3.0
  - future=0.18.3
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - google-auth=2.6.0
  - google-auth-oauthlib=0.5.2
  - graphite2=1.3.14
  - grpcio=1.54.2
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.33
  - h5py=3.8.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.26.0
  - importlib-metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.21.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libarchive=3.6.2
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcups=2.3.3
  - libcurand=10.3.2.56
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libgrpc=1.54.2
  - libhwloc=2.9.0
  - libiconv=1.17
  - libidn2=2.3.2
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libmamba=1.3.1
  - libmambapy=1.3.1
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.44.2
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightning-utilities=0.8.0
  - llvm-openmp=16.0.0
  - llvmlite=0.39.1
  - locket=1.0.0
  - lxml=4.9.2
  - lz4-c=1.9.4
  - lzo=2.10
  - magma=2.6.2
  - mamba=1.3.1
  - markdown=2.6.11
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.31.3
  - mpmath=1.2.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - natsort=7.1.1
  - nbclassic=0.5.3
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nccl=2.14.3.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=2.8.4
  - ninja=1.11.1
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=2.1.0
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openslide-python=1.2.0
  - openssl=3.1.1
  - p11-kit=0.24.1
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.3
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pydensecrf=1.0rc3
  - pygments=2.11.2
  - pyjwt=1.7.1
  - pynndescent=0.5.8
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-spams=2.6.1
  - python_abi=3.8
  - pytorch=1.11.0
  - pytorch-cuda=11.7
  - pytorch-lightning=2.0.0
  - pytorch-model-summary=0.1.1
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.8
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - re2=2023.03.02
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - requests-oauthlib=1.0.0
  - rsa=3.4.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - sip=6.7.7
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - svt-av1=1.4.1
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - torchaudio=0.11.0
  - torchmetrics=0.11.4
  - torchvision=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - umap-learn=0.5.3
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.40.0
  - widgetsnbextension=4.0.5
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - attrs==22.2.0
    - hydra-core==1.3.2
    - lightly==1.4.6
    - lightly-utils==0.0.2
    - multidict==6.0.4
    - omegaconf==2.3.0
    - protobuf==4.23.3
    - setuptools==65.5.1
    - tensorboardx==2.6.1
    - torchsummary==1.5.1
    - yarl==1.8.2
